@startuml Current_Context_Diagram

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml


title Система управления отоплением "Тёплый дом"\nКонтекстная диаграмма (As-Is)


Person(user, "Пользователь\n<size:10>Владелец дома</size>", "Управляет отоплением и смотрит\nтемпературу через веб-интерфейс.")

Person(specialist, "Специалист по подключению\n<size:10>Сотрудник компании</size>", "Физически подключает и\nрегистрирует устройства в системе.")


System(monolith, "Монолитное приложение\n<size:14><b>Тёплый дом</b></size>\n\n- Веб-интерфейс управления\n- Бизнес-логика и API\n- Управление устройствами\n- Хранение всех данных", "Централизованное приложение для управления системой отопления.")

System_Ext(heating_module, "Модуль управления отоплением\n<size:10>Физическое устройство</size>", "Устанавливается в доме пользователя.\nПолучает команды и передаёт данные о температуре.")

System_Ext(temp_sensor, "Датчик температуры\n<size:10>Физический датчик</size>", "Встроен в модуль отопления или установлен отдельно.\nИзмеряет температуру.")

System_Ext(db, "База данных\n<size:10>PostgreSQL</size>", "Хранит:\n- Данные пользователей\n- Информацию об устройствах\n- Команды управления\n- Историю температуры")

' --- Взаимодействия ---
Rel(user, monolith, "Управляет отоплением\nПросматривает температуру", "HTTPS")

Rel(specialist, monolith, "Регистрирует новые устройства", "HTTPS (админ. интерфейс)")

Rel(monolith, heating_module, "Отправляет команды\nВКЛ/ВЫКЛ отопления", "Синхронный HTTP/CoAP")

Rel(monolith, temp_sensor, "Запрашивает текущую\nтемпературу", "Синхронный HTTP/CoAP")

Rel(monolith, db, "Чтение и запись\nвсех данных", "SQL")

@enduml